import speech_recognition as sr
import httpx
import logging
import os
import base64
import struct
import uuid
from app.core.config import settings

logger = logging.getLogger("voice_service")

# Groq OpenAI-compatible Text-to-Speech endpoint.
GROQ_SPEECH_URL = "https://api.groq.com/openai/v1/audio/speech"
GROQ_SPEECH_MODEL = "canopylabs/orpheus-v1-english"
GROQ_SPEECH_VOICE = "troy"
GROQ_SPEECH_MAX_CHARS = 200


def _repack_wav(data: bytes) -> bytes:
    """Repair WAV headers that declare wrong chunk sizes (as Groq's Orpheus does:
    it emits 0xFFFFFFFF placeholders for the RIFF and data sizes). Playback fails /
    shows a bogus duration until these are corrected."""
    if data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        return data

    cur = 12
    fmt_payload = b""
    extra_chunks = []
    data_offset = None
    while cur + 8 <= len(data):
        chunk_id = data[cur : cur + 4]
        size = struct.unpack_from("<I", data, cur + 4)[0]
        if chunk_id == b"data":
            data_offset = cur + 8
            break
        body = data[cur + 8 : min(cur + 8 + size, len(data))]
        if chunk_id == b"fmt ":
            fmt_payload = body
        else:
            extra_chunks.append((chunk_id, body))
        cur += 8 + size + (size & 1)

    if data_offset is None or not fmt_payload:
        return data

    data_payload = data[data_offset:]
    declared_data = struct.unpack_from("<I", data, data_offset - 4)[0]

    # Already valid? Leave it untouched.
    if declared_data != 0xFFFFFFFF and declared_data == len(data_payload):
        return data

    riff_payload = bytearray()
    riff_payload += b"fmt " + struct.pack("<I", len(fmt_payload)) + fmt_payload
    for chunk_id, body in extra_chunks:
        riff_payload += chunk_id + struct.pack("<I", len(body)) + body
        if len(body) & 1:
            riff_payload += b"\x00"
    riff_payload += b"data" + struct.pack("<I", len(data_payload)) + data_payload
    # RIFF chunk size = payload bytes + the 4 "WAVE" ID bytes.
    return b"RIFF" + struct.pack("<I", len(riff_payload) + 4) + b"WAVE" + bytes(riff_payload)


def _extract_audio_bytes(data: bytes, content_type: str) -> bytes:
    """Normalize the Groq TTS response into raw audio bytes.

    Groq returns binary audio (WAV) directly, but some providers/modelines
    return a JSON envelope with base64-encoded audio. Handle both so the
    client always receives real, playable bytes.
    """
    if "json" in (content_type or "").lower() or data.lstrip()[:1] == b"{":
        try:
            payload = __import__("json").loads(data)
        except Exception:
            payload = None
        if isinstance(payload, dict):
            raw = payload.get("data") or payload.get("audio") or payload.get("b64") or payload.get("content")
            if isinstance(raw, str):
                try:
                    return base64.b64decode(raw)
                except Exception:
                    return b""
    return data


class VoiceService:
    @staticmethod
    def audio_content_type(data: bytes) -> str:
        """Pick the correct audio Media Type from the generated bytes (defaults to WAV)."""
        head = data[:12]
        if head.startswith(b"RIFF") and head[8:12] == b"WAVE":
            return "audio/wav"
        if head.startswith(b"ID3") or (len(data) > 1 and data[0] == 0xFF and (data[1] & 0xE0) == 0xE0):
            return "audio/mpeg"
        return "audio/wav"

    @staticmethod
    async def speech_to_text(audio_path: str) -> str:
        import asyncio

        recognizer = sr.Recognizer()
        with sr.AudioFile(audio_path) as source:
            audio = recognizer.record(source)

        def _recognize():
            return recognizer.recognize_google(audio)

        try:
            text = await asyncio.wait_for(asyncio.to_thread(_recognize), timeout=60)
            return text
        except asyncio.TimeoutError:
            return "Speech recognition timed out. Please try again."
        except sr.UnknownValueError:
            return "Could not understand audio"
        except sr.RequestError:
            return "Speech recognition service unavailable"

    @staticmethod
    async def text_to_speech(text: str) -> bytes:
        """Generate speech via Groq (/audio/speech). Returns WAV audio bytes."""
        if not text or not text.strip():
            raise ValueError("Please enter some text to convert to speech.")
        if len(text) > GROQ_SPEECH_MAX_CHARS:
            raise ValueError(
                f"Text must be {GROQ_SPEECH_MAX_CHARS} characters or fewer for Groq TTS "
                f"(current: {len(text)})."
            )
        if not settings.groq_api_key_configured:
            raise RuntimeError("GROQ_API_KEY is not configured on the server")

        payload = {
            "model": GROQ_SPEECH_MODEL,
            "voice": GROQ_SPEECH_VOICE,
            "input": text,
            "response_format": "wav",
        }
        headers = {"Authorization": f"Bearer {settings.GROQ_API_KEY}"}

        try:
            async with httpx.AsyncClient(timeout=60) as client:
                response = await client.post(GROQ_SPEECH_URL, json=payload, headers=headers)
        except httpx.HTTPError as exc:
            # Developer-friendly log; the UI gets a clean generic message.
            logger.error("Groq TTS request error: %s", exc)
            raise RuntimeError("Could not reach the speech service.")

        if response.status_code != 200 or not response.content:
            logger.error(
                "Groq TTS failed (status=%s, model=%s): %s",
                response.status_code,
                GROQ_SPEECH_MODEL,
                response.text[:500],
            )
            raise RuntimeError("The speech service rejected the request.")

        audio = _extract_audio_bytes(
            response.content,
            response.headers.get("content-type", ""),
        )
        if not audio:
            logger.error(
                "Groq TTS returned an empty audio payload (status=%s, model=%s): %s",
                response.status_code,
                GROQ_SPEECH_MODEL,
                response.text[:500],
            )
            raise ValueError("The speech service returned an empty audio file.")
        return _repack_wav(audio)


audio_content_type = VoiceService.audio_content_type
